name: Atualizar README com tópicos dos repositórios

on:
  schedule:
    - cron: "0 6 * * *"  # Roda todo dia às 06:00 UTC
  workflow_dispatch:  # Permite rodar manualmente
  push:
    paths:
      - .github/workflows/update-readme.yml
      - scripts/update_readme.py

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar script de atualização
        run: python scripts/update_readme.py

      - name: Comitar mudanças
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Atualiza README com repositórios por tópico"
          git push
